### ISSUE TITLE
请问编码格式是什么，用GBK、UTF-8、BIG5这些中文格式编码，注释都是乱码

### ISSUE THREAD

**Issue by Chengxxuan** [kt-tian/2021-f-#2]

**Comment by gogongxt** [comment]
GB2312

**Comment by Chengxxuan** [comment]
已收到

**Comment by Chengxxuan** [comment]
感谢！我后来也发现了。




橴煞★藍芯彡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gxt-kt/2021-F-drug_car"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月21日(星期五) 晚上9:46
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [gxt-kt/2021-F-drug_car] 请问编码格式是什么，用GBK、UTF-8、BIG5这些中文格式编码，注释都是乱码 (Issue #2)





 
GB2312
